# Generated by Django 4.1.3 on 2023-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('6', 'Six'), ('8', 'Eight'), ('10', 'Ten'), ('12', 'Twelve'), ('14', 'Fourteen'), ('16', 'Sixteen'), ('18', 'Eighteen'), ('20', 'Twenty')], max_length=4),
        ),
    ]
