# Generated by Django 4.1.3 on 2023-01-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_item_quantity_alter_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
